import localFont from "next/font/local";
import "./globals.css";
import { Analytics } from '@vercel/analytics/next';

const Neue = localFont({
  src: [
    { path: "./fonts/HelveticaNeueBlack.otf", weight: "900", style: "normal" }, // Black
    { path: "./fonts/HelveticaNeueBold.otf", weight: "700", style: "normal" },  // Bold
    { path: "./fonts/HelveticaNeueHeavy.otf", weight: "800", style: "normal" }, // Heavy
    { path: "./fonts/HelveticaNeueLight.otf", weight: "300", style: "normal" }, // Light
    { path: "./fonts/HelveticaNeueMedium.otf", weight: "500", style: "normal" },// Medium
    { path: "./fonts/HelveticaNeueRoman.otf", weight: "400", style: "normal" }, // Roman
    { path: "./fonts/HelveticaNeueThin.otf", weight: "200", style: "normal" },  // Thin
    { path: "./fonts/HelveticaNeueUltraLight.otf", weight: "100", style: "normal" } // Ultralight
  ],
  variable: "--font-neue",
});

const Haas = localFont({
  src: [
    { path: "./fonts/NeueHaasDisplayBlack.ttf", weight: "900", style: "normal" }, // Black
    { path: "./fonts/NeueHaasDisplayBold.ttf", weight: "700", style: "normal" },  // Bold
    { path: "./fonts/NeueHaasDisplayMediu.ttf", weight: "500", style: "normal" },// Medium
    { path: "./fonts/NeueHaasDisplayRoman.ttf", weight: "400", style: "normal" }, // Roman
    { path: "./fonts/NeueHaasDisplayThin.ttf", weight: "200", style: "normal" },  // Thin
    { path: "./fonts/NeueHaasDisplayLight.ttf", weight: "300", style: "normal" }, // Light
  ],
  variable: "--font-haas",
});




export const metadata = {
  title: "Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${Haas.variable} antialiased`}>
        {children}
        <Analytics />
      </body>
    </html>
  );
}
